### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by TrueOleg** [sdamolini/LooksLikeWho#2]
Hi Stephane,

Thanks a lot for creating such a great tool for dealing with face models.

Faced the issues during setting up your project locally. The point is that there is no information (or requirements.txt file) about the dependencies and their versions. Could you please whether point towards this file or add it to the project? 

Thanks in advance

**Comment by sdamolini** [comment]
Hello,

I do not have a requirement file handy, but my env was very specific because of my old graphic card. Please try create a fresh environment compatible with your GPU.

Best,

Stephane
