### ISSUE TITLE
Required files

### ISSUE THREAD

**Issue by TrueOleg** [sdamolini/LooksLikeWho#3]
Hi Stephane,
Since there is requirement file, I setting up the project locally, from time to time there are issues. One of them is - where can I get “encoder_model_weights.h5” and “similarity_model_weights.h5" files to run your project. Could you help me, please?
https://github.com/sdamolini/LooksLikeWho/blob/9ce892976ac5df978d1985d4811663c0d88dbb62/LooksLikeWho/SLD_models.py#L525
https://github.com/sdamolini/LooksLikeWho/blob/9ce892976ac5df978d1985d4811663c0d88dbb62/LooksLikeWho/SLD_models.py#L526

**Comment by sdamolini** [comment]
Hello,

The weights are saved after you train the model, see line 461 and 464:

https://github.com/sdamolini/LooksLikeWho/blob/208ad55a6be1df7825b5252011c6f3a4b372f50e/LooksLikeWho/SLD_models.py#L461

and

https://github.com/sdamolini/LooksLikeWho/blob/208ad55a6be1df7825b5252011c6f3a4b372f50e/LooksLikeWho/SLD_models.py#L464


Regards,

Stephane
